language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
before_script:
- npm install -g gulp-cli
script: gulp
before_deploy:
- git -c user.name="pmlopes" -c user.email="$NPM_EMAIL_ADDRESS" commit -a -m "Release webapp %s [skip ci]"
- npm version patch -m "Release npm %s [skip ci]"
- git -c user.name="pmlopes" -c user.email="$NPM_EMAIL_ADDRESS" push "https://$GITHUB_API_KEY:@github.com/pmlopes/vertx-starter" HEAD:master
deploy:
- provider: npm
  email: "$NPM_EMAIL_ADDRESS"
  api_key: "$NPM_TOKEN"
  on:
    branch: master
- provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  local-dir: dist
  keep-history: true
  on:
    branch: master
env:
  global:
  - secure: v9BgwAQYEjv5H60AwB1jZR2+P69Fka+B1t/NtOC33Ry9eALwBwdt/cCmwzAz9mnQY9NbNCL67CVC82sEqBxtHsWJnY/u7urIe+cp4A/TpdjD/PK8TsLxLj5/PQTXiQi2WP0nXhjAJR/33pSvsfrC6feHnhgwR3kx1uHVbI1bT86WUXOXB+/Pb1j/vyLcPsVCM9Kvm4vA+jsRI0Cu1HvnpdOhFyEMrbsYCIrXkx9DRQNqXvbIbZ0c0lKf9HsHaPXsgMjUZuWXwhzjowM+JtYE88FUNB2GFeX85JH0f2jBbgk8VcodhRazeiLqZwLHbVm8NrZvSwlK/1aClGqxuNoke5lXQ896Bh6jC2Fcf7vfcO4QwdaTiLPp5sEv6sPsUUTKTdbaZ+wGNOy4+IpPqRJG3NQ9fBgA8F+yeimR2Of89jN1OZPjJUhk5GgB4cAoegxf/JBpgQ9ulREyThNG3NPah2x3ffs96mCoT0EYPqGSIYzEfE0h2jSoitTWuaOm2U6CvG+db0zYzWnV6Ncjftq7G1GxvaLk/vQE6SW7f0WQIeuqbW6rPdiPY4u5ZOGTYK18osp4tZPnrxPKz2tKpxOrO24xzHtz4pgqhi1qHNn+4e/MHTotbR/2VcOvMSPx+/pWQX+YTuDFfcI0lxTMjQY2VvNmFRUE0YaMszKTzKnsbIU=
  - secure: VPsweTTc9WyeTC6dCY+A6gDIxJOgnV0wQARJ31ZkkKO8hp+SFyeEaUbo4lfX2QPBnaAqXwxf6gRKf40284wbISxRJnhoJBGuTTHd1gb/683FoXEyH/87MvjFUE/FgVvnG8bP8XrAN65heRIi/8u5IGAAbwpQlVqUB/aSNkdCv/snSkG02OHuz3TlYmIqOanpRv71sLQxWVoVhZzN6OIe2m31VTi3s8r27734UOwSkNsKGcSnLvrfLBwtjx/7jaYOU8GRoTWNbky3PvV4e9mmblgMvXmdOM4EnOUXXYrSMf8wIcMa0oCm67Pcy+UurQZvmA2LeupSyM1zjnJ8Ks5fP6DVPf08Kd6O1AZHrtn3QjkA3nRtsl/g2BijhK1YEb5CbedzwZLcfAGKFwxkMjbVeZzv9HVpOCoO4sS8h7Nj2lrAN9sXN8PWw8ca0EyClXi+b5s3XeTs/EwnMpbJfRcJg7uAmW5ErAmseRwvWQHFawAXArdo4737mQ54Hy8UrG7e0cvMSJRLr0/iGFAPtvPddRucoVriYNL7fWfXA1GusO1RTGNskZSK7Ul90hTgYFDyw37I5Eq7M4h2+v+BGVEwLuS0fH/q0g0TeE319g4w7AbbM3746kgjXP5tgpu+hbGLuZJo0tURzlRofM3ku8rRQHjSOBjg9ksIeNAn4748q3Q=
  - secure: OMc7w7MvJx+JC0lJHlKMhx2aK7ZIE1wM2SDNS2AQRkUZ140lzq0AklZ3oGtqnvsWcX20Om2gFvpwjJIdYFNG2bV0wfc5xI9EGaVqtMDO2g3xIhk+ePKvutyed4+RGsvHFrYPqQCt1ya52zY3S9BGk2IX9ganI2LAHXh2Wx+JW/3eDm2x38UKkV4eTdcBE+OQp9/f1pUq9yTgcD4KgjuKUYhanDBcBGHvNbCpRd+rA/c5Qd7U7YXguB6I8BQc9ixR+n8+z5APf3j1KmgEtVqGPvC6Pa5haaDCFJGrFNI5e+n1QB/+xMjGpx9i3823UY3YdIcNlppUXrHsf/Uu7BeiF4n1x+3D6s85UHnVln+8Dz9VWplcOuPuN39ZK8YypMijVy3TqFMFEIP/TB7PM/2gAHeykZA23mJx4VvPwF510vfK+8V6uIwdJF2m/2N8EWc08RYNAkLKwmFvLBR+Tk1cyck/EFLobA8w4RDN1/QHiZweMM393ET4Poh5OQ4mkKDfMldnpsugbi1FZxIrqTLgrUoquA+uF+bqOeLLhzS4pbPXqG4zqMoAw8JSYZUW58tVh5TQFnJKMG0WrfEz/h9sC8IXGbuc5DOqROg88c00yLg/kaD8n3CrUoSXGDD/TqNKJNADsl5OF/hnNY+NRFbXNaBWen1hQJsh9ZqBvtRuueA=
