language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
before_script:
- npm install -g gulp-cli
script: gulp
deploy:
- provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  local-dir: dist
  keep-history: true
  on:
    branch: master
env:
  global:
    secure: v9BgwAQYEjv5H60AwB1jZR2+P69Fka+B1t/NtOC33Ry9eALwBwdt/cCmwzAz9mnQY9NbNCL67CVC82sEqBxtHsWJnY/u7urIe+cp4A/TpdjD/PK8TsLxLj5/PQTXiQi2WP0nXhjAJR/33pSvsfrC6feHnhgwR3kx1uHVbI1bT86WUXOXB+/Pb1j/vyLcPsVCM9Kvm4vA+jsRI0Cu1HvnpdOhFyEMrbsYCIrXkx9DRQNqXvbIbZ0c0lKf9HsHaPXsgMjUZuWXwhzjowM+JtYE88FUNB2GFeX85JH0f2jBbgk8VcodhRazeiLqZwLHbVm8NrZvSwlK/1aClGqxuNoke5lXQ896Bh6jC2Fcf7vfcO4QwdaTiLPp5sEv6sPsUUTKTdbaZ+wGNOy4+IpPqRJG3NQ9fBgA8F+yeimR2Of89jN1OZPjJUhk5GgB4cAoegxf/JBpgQ9ulREyThNG3NPah2x3ffs96mCoT0EYPqGSIYzEfE0h2jSoitTWuaOm2U6CvG+db0zYzWnV6Ncjftq7G1GxvaLk/vQE6SW7f0WQIeuqbW6rPdiPY4u5ZOGTYK18osp4tZPnrxPKz2tKpxOrO24xzHtz4pgqhi1qHNn+4e/MHTotbR/2VcOvMSPx+/pWQX+YTuDFfcI0lxTMjQY2VvNmFRUE0YaMszKTzKnsbIU=
