language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
before_script:
- npm install -g gulp-cli
script:
- npm version --no-git-tag-version 0.1.$TRAVIS_BUILD_NUMBER
- npm run build
deploy:
- provider: npm
  skip_cleanup: true
  email: "$NPM_EMAIL_ADDRESS"
  api_key: "$NPM_TOKEN"
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^master|develop$"
- provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  local-dir: dist
  keep-history: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^master|develop$"
env:
  global:
  - secure: 3mSa2r485psD3IjqWt4C3OoyDZYjzpSQGw2zQQG4Z51LTOg4L/ArQxUDa83f0yKbKc7ETatetx/90rFj9MBtWhepj/aNNo7CsLhbjwsvmynTyFqwUW/kIltwOOSgzKtoWBK6eCMBCHTMM4rDyKnSAVHTNWiy/hiG2OdX1/58aG6t1ZM+5uyt768f/pAfeGBYW/ARWq71Gi0g8KGq0TpIPSUBvm+97vIbkyzpsY/HwVf9h7pxbljKji6u6mgvZAU1u8nTLqaSZKL/RYGFyU0No9jCWoihRUgegv3i1P5AvmCmxUE1VlNlOs9QXFAHmEGKlC0r6Xr/L9bYTMNUK8tnsBDD5q5OtbWd1qfQpJ1bjy3FFfiBZxqj/8iEU5WWZfnfo92jMWUsTTOC0ftrph3WQGaEYtz7lEeIXwwnM0bzf2WePrCEpavbSGGBHCEpbtzUCumIY9GG1wz7cTP+r0aIzkV40iDueexR0t5Ikj5uEtmIgaMiVT/YqORtE2DVEOx+o+w0pa0+xBj7ABYNO862/EaZZU46fKvSfZdzvdaddAJsPGnqi2/WePLFYgypRIyPnind+VmQLoZt+OkkykuR5Z0uaAkUHhZlEQtn/keEO7E4njwEO8JmZ47Pb+cFFlwxPaC0paxuBVJAnK19N1i5yioa0O/OsAAywcQQbaDv6Qo=
  - secure: VPsweTTc9WyeTC6dCY+A6gDIxJOgnV0wQARJ31ZkkKO8hp+SFyeEaUbo4lfX2QPBnaAqXwxf6gRKf40284wbISxRJnhoJBGuTTHd1gb/683FoXEyH/87MvjFUE/FgVvnG8bP8XrAN65heRIi/8u5IGAAbwpQlVqUB/aSNkdCv/snSkG02OHuz3TlYmIqOanpRv71sLQxWVoVhZzN6OIe2m31VTi3s8r27734UOwSkNsKGcSnLvrfLBwtjx/7jaYOU8GRoTWNbky3PvV4e9mmblgMvXmdOM4EnOUXXYrSMf8wIcMa0oCm67Pcy+UurQZvmA2LeupSyM1zjnJ8Ks5fP6DVPf08Kd6O1AZHrtn3QjkA3nRtsl/g2BijhK1YEb5CbedzwZLcfAGKFwxkMjbVeZzv9HVpOCoO4sS8h7Nj2lrAN9sXN8PWw8ca0EyClXi+b5s3XeTs/EwnMpbJfRcJg7uAmW5ErAmseRwvWQHFawAXArdo4737mQ54Hy8UrG7e0cvMSJRLr0/iGFAPtvPddRucoVriYNL7fWfXA1GusO1RTGNskZSK7Ul90hTgYFDyw37I5Eq7M4h2+v+BGVEwLuS0fH/q0g0TeE319g4w7AbbM3746kgjXP5tgpu+hbGLuZJo0tURzlRofM3ku8rRQHjSOBjg9ksIeNAn4748q3Q=
  - secure: OMc7w7MvJx+JC0lJHlKMhx2aK7ZIE1wM2SDNS2AQRkUZ140lzq0AklZ3oGtqnvsWcX20Om2gFvpwjJIdYFNG2bV0wfc5xI9EGaVqtMDO2g3xIhk+ePKvutyed4+RGsvHFrYPqQCt1ya52zY3S9BGk2IX9ganI2LAHXh2Wx+JW/3eDm2x38UKkV4eTdcBE+OQp9/f1pUq9yTgcD4KgjuKUYhanDBcBGHvNbCpRd+rA/c5Qd7U7YXguB6I8BQc9ixR+n8+z5APf3j1KmgEtVqGPvC6Pa5haaDCFJGrFNI5e+n1QB/+xMjGpx9i3823UY3YdIcNlppUXrHsf/Uu7BeiF4n1x+3D6s85UHnVln+8Dz9VWplcOuPuN39ZK8YypMijVy3TqFMFEIP/TB7PM/2gAHeykZA23mJx4VvPwF510vfK+8V6uIwdJF2m/2N8EWc08RYNAkLKwmFvLBR+Tk1cyck/EFLobA8w4RDN1/QHiZweMM393ET4Poh5OQ4mkKDfMldnpsugbi1FZxIrqTLgrUoquA+uF+bqOeLLhzS4pbPXqG4zqMoAw8JSYZUW58tVh5TQFnJKMG0WrfEz/h9sC8IXGbuc5DOqROg88c00yLg/kaD8n3CrUoSXGDD/TqNKJNADsl5OF/hnNY+NRFbXNaBWen1hQJsh9ZqBvtRuueA=
